import test from 'node:test';
import assert from 'node:assert/strict';
import {makeRoom,newPlayer,applyAction,publicState,destinations,runBots} from '../lib/game.ts';
function two(){const s=makeRoom('ABC234','session1','First','Violent J');const q=newPlayer('session2','Second','Shaggy 2 Dope',1);q.ready=true;s.players.push(q);applyAction(s,s.host,{type:'start'});return s}
test('requires a second player and ready seats',()=>{const s=makeRoom('ABC234','s','First','Violent J');assert.throws(()=>applyAction(s,s.host,{type:'start'}),/two players/);s.players.push(newPlayer('s2','Second','Blaze',1));assert.throws(()=>applyAction(s,s.host,{type:'start'}),/ready/)});
test('turns reject another player, repeat roll, illegal moves, premature end',()=>{const s=two(),p=s.players[s.turn],other=s.players.find(x=>x.id!==p.id);assert.throws(()=>applyAction(s,other.id,{type:'roll'}),/Wait/);applyAction(s,p.id,{type:'roll'});assert.throws(()=>applyAction(s,p.id,{type:'roll'}),/already rolled/);assert.throws(()=>applyAction(s,p.id,{type:'move',region:3,pos:0}),/highlighted/);assert.throws(()=>applyAction(s,p.id,{type:'end'}),/Finish/);const d=s.choices[0];applyAction(s,p.id,{type:'move',...d});assert.equal(s.phase,'encounter')});
test('cards and finale are hidden until revealed; credentials never leave server',()=>{const s=two();const pub=publicState(s,'session1');assert.equal(pub.finale,null);assert.equal(pub.decks,undefined);assert.ok(pub.players.every(p=>p.session===undefined));assert.equal(pub.me,s.players[0].id)});
test('prototype passages enforce cash and base combat requirements',()=>{const s=two(),p=s.players[0];p.pos=11;p.cash=0;assert.ok(destinations(p,1).every(d=>d.region===0));p.cash=100;assert.ok(destinations(p,1).some(d=>d.region===1&&d.pos===8&&d.toll===100));p.region=2;p.pos=6;p.bonus=14;p.weapon=10;assert.ok(destinations(p,1).every(d=>d.region!==3));p.bonus=15;assert.ok(destinations(p,1).some(d=>d.region===3));});
test('cannot discard an unresolved encounter by drawing again',()=>{const s=two(),p=s.players[s.turn];s.phase='encounter';s.encounter={id:'test',kind:'cash',name:'Test',value:100,text:'Take $100.'};assert.throws(()=>applyAction(s,p.id,{type:'draw'}),/Finish/);applyAction(s,p.id,{type:'resolve'});assert.equal(p.cash,400);assert.equal(s.phase,'end');assert.equal(s.encounter,null)});
test('healing is capped and zero-stock tonic cannot be used',()=>{const s=two(),p=s.players[s.turn];p.life=4;applyAction(s,p.id,{type:'tonic'});assert.equal(p.life,5);assert.equal(p.tonics,0);assert.throws(()=>applyAction(s,p.id,{type:'tonic'}),/tonic/)});
test('only host controls start and practice opponents; character uniqueness checked',()=>{const s=makeRoom('ABC234','s','First','Violent J');s.players.push(newPlayer('s2','Second','Blaze',1));assert.throws(()=>applyAction(s,s.players[1].id,{type:'add-bot'}),/host/);assert.throws(()=>applyAction(s,s.players[1].id,{type:'character',character:'Violent J'}),/already/)});
test('death has only one return before elimination',()=>{const s=two(),p=s.players[s.turn];s.phase='encounter';p.life=1;s.encounter={id:'trap',kind:'hazard',name:'Trap',value:1,text:'Lose 1 life.'};applyAction(s,p.id,{type:'resolve'});assert.equal(p.rebirth,true);assert.equal(p.life,5);assert.equal(p.dead,false);p.life=1;s.phase='encounter';s.encounter={id:'trap2',kind:'hazard',name:'Trap',value:1,text:'Lose 1 life.'};applyAction(s,p.id,{type:'resolve'});assert.equal(p.dead,true);assert.equal(s.status,'finished')});
test('practice opponent completes turns and returns control to a human',()=>{const s=makeRoom('ABC234','s','First','Violent J');applyAction(s,s.host,{type:'add-bot'});applyAction(s,s.host,{type:'start'});s.turn=1;runBots(s);assert.equal(s.players[s.turn].bot,undefined);assert.equal(s.phase,'roll')});
test('several complete games terminate with a valid winner',()=>{for(let game=0;game<10;game++){const s=two();let steps=0;while(s.status==='playing'&&steps++<4000){const p=s.players[s.turn];if(p.life<3&&p.tonics>0)applyAction(s,p.id,{type:'tonic'});if(s.phase==='roll')applyAction(s,p.id,{type:'roll'});else if(s.phase==='move'){const sorted=[...s.choices].sort((a,b)=>b.region-a.region);const d=p.bonus>=[6,10,15][p.region]?sorted[0]:sorted.find(d=>d.region===p.region)??sorted[0];applyAction(s,p.id,{type:'move',...d})}else if(s.phase==='encounter')applyAction(s,p.id,{type:s.encounter?'resolve':'draw'});else if(s.phase==='combat')applyAction(s,p.id,{type:'fight'});else applyAction(s,p.id,{type:'end'});for(const p of s.players){assert.ok(p.cash>=0);assert.ok(p.life>=0&&p.life<=p.maxLife);assert.ok(p.bonus>=0&&p.bonus<=25)}}assert.equal(s.status,'finished');assert.ok(s.players.some(p=>p.id===s.winner));}});

test('a fatal hazard returns to its source deck after player rebirth',()=>{const s=two(),p=s.players[s.turn];p.region=2;p.life=1;s.phase='encounter';s.encounter={id:'2-e6',kind:'hazard',name:'Trap',value:1,text:'Lose 1 life.'};applyAction(s,p.id,{type:'resolve'});assert.equal(p.region,0);assert.equal(s.discards[2].length,1);assert.equal(s.discards[0].length,0)});
