'use client';
import board from '@/lib/board.json';
import {GATES,REGIONS} from '@/lib/game';
export {REGIONS} from '@/lib/game';
export function spaceName(r:number,p:number){return r===3?'Shangri-La':board.regions[r]?.[p]??'Unknown space'}
export default function Board({players=[],choices=[],onMove,active,disabled=false}:{players?:{id:string;name:string;region:number;pos:number;color:string;dead?:boolean}[];choices?:{region:number;pos:number}[];onMove?:(r:number,p:number)=>void;active?:string;disabled?:boolean}){return <div className="board-wrap"><div className="photo-board"><img src="/board-reference.jpg" alt="The Quest for Shangri-La original board reference photograph"/><svg viewBox="0 0 800 800" aria-label="Game board; highlighted spaces are legal destinations">
 {board.spaces.map((spaces,r)=>spaces.map(s=>{const selected=choices.some(c=>c.region===r&&c.pos===s.index);return <g key={`${r}:${s.index}`}><rect x={s.column*100+4} y={s.row*100+4} width="92" height="92" rx="6" className={selected?'board-space legal':'board-space'} role={selected?'button':undefined} tabIndex={selected&&!disabled?0:undefined} aria-label={selected?`Move to ${s.name}, ${REGIONS[r]} ${s.index+1}`:`${s.name} · ${REGIONS[r]} ${s.index+1}`} onClick={()=>selected&&!disabled&&onMove?.(r,s.index)} onKeyDown={e=>{if(selected&&!disabled&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onMove?.(r,s.index)}}}/>{s.index===GATES[r]&&<g pointerEvents="none"><circle cx={s.column*100+82} cy={s.row*100+18} r="12" fill="#16131c" stroke="#e7c375" strokeWidth="2"/><text x={s.column*100+82} y={s.row*100+24} fill="#ffe0a2" fontSize="18" textAnchor="middle">◇</text></g>}</g>}))}
 <rect x="307" y="307" width="186" height="186" rx="12" className={choices.some(c=>c.region===3)?'board-space legal center-patch':'center-patch'} onClick={()=>!disabled&&choices.some(c=>c.region===3)&&onMove?.(3,0)} role={choices.some(c=>c.region===3)?'button':undefined} tabIndex={choices.some(c=>c.region===3)&&!disabled?0:undefined} aria-label="Enter Shangri-La" onKeyDown={e=>{if(!disabled&&choices.some(c=>c.region===3)&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onMove?.(3,0)}}}/><text x="400" y="365" className="center-small" style={{fontSize:13}}>THE QUEST FOR</text><text x="400" y="401" className="center-title" style={{fontSize:32}}>Shangri-La</text><text x="400" y="430" className="center-small" style={{fontSize:12}}>COMBAT BONUS 15+</text>
 {players.filter(p=>!p.dead).map(p=>{const q=board.spaces[p.region]?.[p.pos],same=players.filter(o=>!o.dead&&o.region===p.region&&o.pos===p.pos),i=same.findIndex(o=>o.id===p.id);return <g key={p.id} transform={`translate(${(q?q.column*100+50:400)+(i-(same.length-1)/2)*27},${q?q.row*100+52:467})`} pointerEvents="none"><circle r={p.id===active?24:20} fill={p.color} stroke={p.id===active?'white':'#111'} strokeWidth="4"/><text y="7" className="pawn-letter" style={{fontSize:20}}>{p.name[0]?.toUpperCase()}</text></g>})}
 </svg></div><div className="board-legend"><span><i className="red"/>Detroit</span><span><i className="violet"/>Nethervoid</span><span><i className="gold"/>Dark Carnival</span></div></div>}
